name: Linux Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install -y libgmp-dev libmpfr-dev libmpc-dev
        pip install -r requirements.txt
        pip install python-coveralls
        pip install pytest-cov
        pip install -e .
    - name: Test with pytest
      run: |
        py.test --cov=hwtypes tests/
    - name: Install deploy packages
      shell: bash -l {0}
      run: |
        pip install twine
    - name: Upload to PyPI
      shell: bash -l {0}
      run: |
        python setup.py sdist build
        twine upload dist/* -u leonardt -p $PYPI_PASSWORD
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
