name: Linux Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y libgmp-dev libmpfr-dev libmpc-dev
        git clone https://github.com/aleaxit/gmpy
        cd gmpy
        python setup.py install
        cd ..
        pip install -r requirements.txt
        pip install pytest
        pip install -e .
    - name: Test with pytest
      run: |
        py.test tests/
    - name: Install deploy packages
      shell: bash -l {0}
      run: |
        pip install twine
    - name: Upload to PyPI
      shell: bash -l {0}
      run: |
        python setup.py sdist build
        twine upload dist/* -u leonardt -p $PYPI_PASSWORD
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
